package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author MaiTrinh
 */
import GUI.EmployeeContentPanel;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class MainForm extends javax.swing.JFrame implements MouseListener {

    private JLabel selectedMenuItem = null;
    private EmployeeContentPanel employeeContentPanel;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        employeeContentPanel = new EmployeeContentPanel();
        
        staffLabel.addMouseListener(this);
        profileLabel.addMouseListener(this);
        
        contentPanel.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        manageMenu = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        staffLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        projectLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        rewardLabel = new javax.swing.JLabel();
        statsLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 800));

        menuPanel.setBackground(new java.awt.Color(204, 204, 204));
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 700));

        manageMenu.setBackground(new java.awt.Color(204, 204, 204));
        manageMenu.setLayout(new java.awt.GridLayout(9, 1));

        profileLabel.setBackground(new java.awt.Color(102, 102, 102));
        profileLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/profile.png"))); // NOI18N
        profileLabel.setText("Trang cá nhân");
        profileLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profileLabel.setOpaque(true);
        manageMenu.add(profileLabel);

        staffLabel.setBackground(new java.awt.Color(102, 102, 102));
        staffLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        staffLabel.setForeground(new java.awt.Color(255, 255, 255));
        staffLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/staff.png"))); // NOI18N
        staffLabel.setText("Quản lý nhân viên");
        staffLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        staffLabel.setOpaque(true);
        manageMenu.add(staffLabel);

        departmentLabel.setBackground(new java.awt.Color(102, 102, 102));
        departmentLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        departmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        departmentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/department.png"))); // NOI18N
        departmentLabel.setText("Quản lý phòng ban");
        departmentLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        departmentLabel.setOpaque(true);
        manageMenu.add(departmentLabel);

        projectLabel.setBackground(new java.awt.Color(102, 102, 102));
        projectLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        projectLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/project.png"))); // NOI18N
        projectLabel.setText("Quản lý dự án");
        projectLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projectLabel.setOpaque(true);
        manageMenu.add(projectLabel);

        salaryLabel.setBackground(new java.awt.Color(102, 102, 102));
        salaryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        salaryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/salary.png"))); // NOI18N
        salaryLabel.setText("Quản lý lương");
        salaryLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salaryLabel.setOpaque(true);
        manageMenu.add(salaryLabel);

        rewardLabel.setBackground(new java.awt.Color(102, 102, 102));
        rewardLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rewardLabel.setForeground(new java.awt.Color(255, 255, 255));
        rewardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/medal.png"))); // NOI18N
        rewardLabel.setText("Quản lý khen thưởng");
        rewardLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rewardLabel.setOpaque(true);
        manageMenu.add(rewardLabel);

        statsLabel.setBackground(new java.awt.Color(102, 102, 102));
        statsLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statsLabel.setForeground(new java.awt.Color(255, 255, 255));
        statsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/stats.png"))); // NOI18N
        statsLabel.setText("Thống kê");
        statsLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statsLabel.setOpaque(true);
        manageMenu.add(statsLabel);

        accountLabel.setBackground(new java.awt.Color(102, 102, 102));
        accountLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/account.png"))); // NOI18N
        accountLabel.setText("Quản lý tài khoản");
        accountLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        accountLabel.setOpaque(true);
        manageMenu.add(accountLabel);

        logoutLabel.setBackground(new java.awt.Color(102, 102, 102));
        logoutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Icons/logout.png"))); // NOI18N
        logoutLabel.setText("Đăng xuất");
        logoutLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logoutLabel.setOpaque(true);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(manageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(manageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        contentPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        contentPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)))
        );

        contentPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        JLabel clickedLabel = (JLabel) e.getSource();

        System.out.println(selectedMenuItem);
        
        // Reset background của label trước đó (nếu có)
        if (selectedMenuItem != null) {
            selectedMenuItem.setOpaque(false);
            selectedMenuItem.setBackground(new Color(102, 102, 102)); // Màu nền mặc định
        }

        // Cập nhật label được chọn và thay đổi màu nền
        selectedMenuItem = clickedLabel;
        clickedLabel.setOpaque(true);
        clickedLabel.setBackground(new Color(30, 30, 30)); // Màu nền nhấn vào

        // Xử lý chuyển đổi content panel dựa vào label được nhấn
        if (clickedLabel == staffLabel) {
            showEmployeeContentPanel();
        } else if (clickedLabel == profileLabel) {
            showProfileContentPanel();
        }
        
    }

    private void showEmployeeContentPanel() {
        contentPanel.removeAll(); // Xóa nội dung cũ
        contentPanel.add(employeeContentPanel); // Thêm panel mới (Giả sử bạn có EmployeePanel)
        contentPanel.revalidate();
        contentPanel.repaint();
    }
    
    private void showProfileContentPanel() {
        contentPanel.removeAll();
        contentPanel.revalidate();
        contentPanel.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel manageMenu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel rewardLabel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel staffLabel;
    private javax.swing.JLabel statsLabel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
