/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Stats;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author MaiTrinh
 */
public class StatisticContentPanel extends javax.swing.JPanel implements MouseListener {

    private JLabel selectedMenuItem;
    private EmplStats emplStats;
    private ProjectStats prjStats;
    private SalaryStats salaryStats;

    /**
     * Creates new form StatisticContentPanel
     */
    public StatisticContentPanel() {
        initComponents();
        jPanel2.setLayout(new BorderLayout());

        lblEmpl.addMouseListener(this);
        lblProject.addMouseListener(this);
        lblSalary.addMouseListener(this);

        selectedMenuItem = lblEmpl;
        selectedMenuItem.setOpaque(true);
        selectedMenuItem.setBackground(new Color(255, 255, 255));
        selectedMenuItem.setForeground(Color.BLACK);
        emplStats = new EmplStats();

        jPanel2.removeAll();
        if (emplStats != null) {
            jPanel2.add(emplStats);
        }
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmpl = new javax.swing.JLabel();
        lblProject = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblEmpl.setBackground(new java.awt.Color(102, 102, 102));
        lblEmpl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmpl.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpl.setText("Nhân viên");
        lblEmpl.setOpaque(true);

        lblProject.setBackground(new java.awt.Color(102, 102, 102));
        lblProject.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblProject.setForeground(new java.awt.Color(255, 255, 255));
        lblProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProject.setText("Dự án");
        lblProject.setOpaque(true);

        lblSalary.setBackground(new java.awt.Color(102, 102, 102));
        lblSalary.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalary.setText("Lương");
        lblSalary.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(lblEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblProject, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProject, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 120, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEmpl;
    private javax.swing.JLabel lblProject;
    private javax.swing.JLabel lblSalary;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        JLabel clickedLabel = (JLabel) e.getSource();

        // Reset background của label trước đó
        if (selectedMenuItem != null) {
            // selectedMenuItem.setOpaque(false);
            selectedMenuItem.setBackground(new Color(102, 102, 102));
            selectedMenuItem.setForeground(Color.WHITE);
        }

        // Cập nhật lại label được chọn
        selectedMenuItem = clickedLabel;
        clickedLabel.setOpaque(true);
        clickedLabel.setBackground(new Color(255, 255, 255));
        clickedLabel.setForeground(Color.BLACK);
        if (selectedMenuItem == lblEmpl) {
            emplStats = new EmplStats();
            jPanel2.removeAll();
            if (emplStats != null) {
                jPanel2.add(emplStats);
            }
            jPanel2.revalidate();
            jPanel2.repaint();
        } else {
            if (selectedMenuItem == lblProject) {
                prjStats = new ProjectStats();
                jPanel2.removeAll();
                if (prjStats != null) {
                    jPanel2.add(prjStats);
                }
                jPanel2.revalidate();
                jPanel2.repaint();
            } else {
                if (selectedMenuItem == lblSalary) {
                    salaryStats = new SalaryStats();
                    jPanel2.removeAll();
                    if (salaryStats != null) {
                        jPanel2.add(salaryStats);
                    }
                    jPanel2.revalidate();
                    jPanel2.repaint();
                }
            }
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }
}
